name: Build and Deploy to GitHub Pages #

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch
      
permissions:
  id-token: write
  pages: write
  
jobs:
  build:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Use Node.js # Set up the Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '22' # Specify your required Node.js version

    - name: Install dependencies
      run: npm install # Installs your project dependencies

    - name: Build the React app
      run: npm run build # Runs the build command (often creates a 'build' or 'dist' folder)
    - name: Upload static files as artifact
      id: upload
      uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
      with:
        path: dist/
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
